# -*- coding: utf-8 -*-
"""Analisi_Tempi_di_valutazione.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SSRKwEoagssu43yJotTqtLJ5SOrpyxaj
"""

import pandas as pd
from datetime import datetime

def time_to_ms(time):
  time_obj = datetime.strptime(time, "%H:%M:%S")
  total_ms = (time_obj.hour * 3600 + time_obj.minute * 60 + time_obj.second) * 1000
  return total_ms

def max_elab_time_and_rows(analisis_df):
  elab_time_max = df["Time"].max()
  rows = df[df["Time"] == elab_time_max]["Righe"]
  return elab_time_max, rows

file_path = "Tempi_di_valutazione_CodeGen.csv"
df = pd.read_csv(file_path, header=None, names=['Righe', 'Time'], quotechar='"')

print(df)

times = [time_to_ms(time) for time in df["Time"]]
df["Time"] = times
print(df["Time"])

print(df)

df_Analisi = pd.read_excel("AnalisiCodeGen.xlsx")

elab_time_max,rows = max_elab_time_and_rows(df)

print(elab_time_max)
print(rows[0])

rows = rows[0].split(",")

rows = [int(r) for r in rows]

for row in rows:
  print(df_Analisi["IN"][row-2])