# -*- coding: utf-8 -*-
"""Analisi_Tempi_di_valutazione.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SSRKwEoagssu43yJotTqtLJ5SOrpyxaj
"""

import pandas as pd
from datetime import datetime
from scipy.stats import spearmanr, kendalltau

metrics_name = ["EM_M","ED_M","METEOR_M"]

file_to_analize = "AnalisiCodeGen.xlsx"
df_corr_file = pd.read_excel(file_to_analize)

HE_M = df_corr_file["HUMAN_E"]

for metric in metrics_name:
  print(f"Analizyng {metric}...")
  spearman_corr, spearman_p_value = spearmanr(HE_M, df_corr_file[metric])
  kendall_corr, kendall_p_value = kendalltau(HE_M, df_corr_file[metric])

  print("Spearman Correlation:", spearman_corr)
  print("Spearman P-value:", spearman_p_value)

  print("Kendall Correlation:", kendall_corr)
  print("Kendall P-value:", kendall_p_value)

  print("\n\n")